### ISSUE TITLE
Issue with glottals

### ISSUE THREAD

**Issue by julesbouton** [t92jp/ipa2tipa#2]
Hi !
Nice script, very useful thank you !

I noticed the following error :
glottal stop ˀ should be \super P (instead of \super Q, which returns the glottal stop)

**Comment by t92jp** [comment]
Hi @julesbouton, thank you for using my script and reporting an issue!
I recognized the error you mention and I have made a commit `5467e0` that should fix it.

**Comment by julesbouton** [comment]
Thanks! (and sorry for seeing this only now)
